# Generated by Django 4.1.5 on 2023-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_newuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
