# Generated by Django 4.1.5 on 2023-09-04 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='pin',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Invalid pin', regex='^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]{7}$')]),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='client_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
