# Generated by Django 4.1.5 on 2023-09-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newuser_pin_alter_newuser_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='birthdate',
            field=models.DateField(default=None, null=True),
        ),
    ]
